[package]
name = "device-sys"
version = "0.1.0"
edition = "2021"
links = "device"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.83"

[dependencies]
cc = "1.0.83"